build:
  npm_install:
    image: node
    commands:
      - npm install
      - npm run postinstall
  test:
    image: node
    commands:
      - npm run test-single-run
  build:
    image: node
    commands:
      - npm run build
  package:
    image: alpine
    commands:
      - tar cf package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar dist
      - gzip package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar
      - echo jorge prueba que funcione primero con "drone exec" antes de hacer push

# al hacer esto el directorio node_modules queda cacheado en el server de CI y no hay que bajar todo cada vez
cache:
  mount:
    - node_modules
